import { useEffect,useMemo,useState } from "react";
import { ArrowLeft,CircleStop,FolderOpen,Pencil,Play,Sparkles } from "lucide-react";
import { acceptedResponseNotes,pitchNames,userNotes,type StarScoreProject } from "@starscore/core";
import { getProject } from "../storage/projectRepository";
import { audioEngine } from "../audio/AudioEngine";
import { StarCanvas } from "../studio/StarCanvas";
import { AccessibleNoteList } from "../components/AccessibleNoteList";
import { MotionToggle } from "../components/MotionToggle";
import { publishPreviewProject } from "../preview/bridge";
import { AppNavigation } from "../components/AppNavigation";
import { projectOrigins, projectRoute, type ProjectOrigin } from "../navigation/projectRoutes";

export function PlayerPage({projectId,origin,originGalaxyId,navigate}:{projectId:string;origin?:ProjectOrigin;originGalaxyId?:string;navigate:(hash:string)=>void}){const[project,setProject]=useState<StarScoreProject|null>(null);const[status,setStatus]=useState<"loading"|"ready"|"missing"|"error">("loading");const[playing,setPlaying]=useState(false);const[activeId,setActiveId]=useState<string|null>(null);const[progress,setProgress]=useState(0);
  const returnTo=origin==="community"&&originGalaxyId?{...projectOrigins.community,hash:`#/community/${encodeURIComponent(originGalaxyId)}`}:origin?projectOrigins[origin]:projectOrigins.library;
  const editHash=projectRoute("studio",projectId,origin,originGalaxyId);
  useEffect(()=>{let current=true;setStatus("loading");getProject(projectId).then(value=>{if(!current)return;if(value){setProject(value);setStatus("ready")}else setStatus("missing")}).catch(()=>current&&setStatus("error"));return()=>{current=false;audioEngine.dispose()}},[projectId]);
  const stop=()=>{audioEngine.stop();setPlaying(false);setActiveId(null);setProgress(0)};
  const play=async()=>{if(!project)return;try{setPlaying(true);await audioEngine.play(project,{onNote:setActiveId,onProgress:setProgress,onEnded:()=>setPlaying(false)})}catch{setPlaying(false);setStatus("error")}};
  const toggle=(track:"lead"|"bass"|"drums",enabled:boolean)=>setProject(value=>value?{...value,mixer:{...value.mixer,[track]:{...value.mixer[track],enabled}}}:value);
  const originals=useMemo(()=>project?userNotes(project):[],[project]);const response=useMemo(()=>project?acceptedResponseNotes(project):[],[project]);
  useEffect(()=>{if(project)publishPreviewProject(project,playing)},[project,playing]);
  useEffect(()=>{const back=(event:Event)=>{event.preventDefault();stop();navigate(editHash)};window.addEventListener("starscore:native-back",back);return()=>window.removeEventListener("starscore:native-back",back)},[editHash]);
  if(status!=="ready"||!project)return <div className="app"><header className="topbar"><div className="brand"><div className="brand-mark"><Sparkles size={21}/></div><div><h1>星谱</h1><small>STARSCORE</small></div></div></header><AppNavigation active={origin} nested={Boolean(origin)} navigate={navigate}/><main className="recovery"><Sparkles size={30}/><h2>{status==="loading"?"正在读取星图…":status==="missing"?"这颗星图不在本机":"作品读取失败"}</h2><p>{status==="missing"?"本地作品可能已移动。可以返回我的星系重新选择，或导入项目文件。":"现有本地作品不会被修改，请返回后重试。"}</p><div><button onClick={()=>navigate(returnTo.hash)}><FolderOpen size={17}/>返回{returnTo.label}</button><button onClick={()=>navigate(editHash)}><ArrowLeft size={17}/>返回创作</button></div></main></div>;
  return <div className="app player-page"><header className="topbar"><div className="brand"><div className="brand-mark"><Sparkles size={21}/></div><div><h1>星谱</h1><small>PLAY MODE</small></div></div><nav className="top-actions"><MotionToggle/><button className="new-button" onClick={()=>navigate(editHash)}><Pencil size={17}/>编辑作品</button></nav></header><AppNavigation active={origin} nested={Boolean(origin)} navigate={hash=>{stop();navigate(hash==="#/studio"?editHash:hash)}}/><main className="player-workspace"><button className="text-button" onClick={()=>navigate(returnTo.hash)}><ArrowLeft size={17}/>返回{returnTo.label}</button><div className="player-heading"><div><p className="eyebrow">CONSTELLATION PERFORMANCE</p><h2>{project.title}</h2><p>90 BPM · C 五声音阶 · {project.responseMeta?.provider==="model"?"AI 回应":project.responseMeta?.candidateId.startsWith("catalog-")?"素材预设回应":project.responseMeta?"规则演示回应":"仅原旋律"}</p></div><div className="player-switches">{(["lead","bass","drums"] as const).map(track=><label key={track}><input type="checkbox" checked={project.mixer[track].enabled} onChange={event=>{stop();toggle(track,event.target.checked)}}/><span>{track==="lead"?"旋律":track==="bass"?"低音":"节奏"}</span></label>)}</div></div><section className="player-canvas"><StarCanvas readOnly notes={originals} candidateNotes={response} layout={project.layout.notes} selectedId={null} activeId={activeId} progress={progress} reconnectFromId={null} onDragStart={()=>{}} onDragCommit={()=>{}} onSelect={()=>{}} onCreate={()=>{}} onMove={()=>{}}/><div className="player-transport">{playing?<button onClick={stop} aria-label="停止演奏"><CircleStop size={27}/>停止</button>:<button onClick={()=>void play()} aria-label="播放作品"><Play size={27} fill="currentColor"/>播放作品</button>}<span>{activeId?`正在点亮 ${pitchNames[project.tracks.lead.events.find(note=>note.id===activeId)?.pitch??0]??"星点"}`:playing?"等待下一颗星":"准备演奏四小节"}</span></div></section><AccessibleNoteList notes={project.tracks.lead.events} readonly/></main></div>}
