import assert from 'node:assert/strict';
import { applyResponseCandidate, createNightSailProject, createResponseRequest, exportProjectJson, importProjectJson, userNotes, validateProject } from '@starscore/core';
import { exportProjectMidi, inspectMidi } from '../apps/web/src/files/midi';
import { initialStudioState, studioReducer } from '../apps/web/src/studio/studioReducer';

(globalThis as any).window={__STARSCORE_HTML_PREVIEW__:true};
const {requestResponses,getAiHealth}=await import('../apps/web/src/ai/client');
const {downloadHref}=await import('../apps/web/src/files/download');
const project=createNightSailProject();
assert.equal(userNotes(project).length,6);
assert.deepEqual(validateProject(project),[]);
assert.deepEqual(await getAiHealth(),{ok:true,modelConfigured:false});
const request=createResponseRequest(project,'preview-validation','rules');
const payload=await requestResponses(request,new AbortController().signal);
assert.equal(payload.candidates.length,2);
(globalThis as any).window.__STARSCORE_HTML_PREVIEW__=false;
const offlinePayload=await requestResponses({...request,requestId:'formal-offline-rules'},new AbortController().signal);
assert.equal(offlinePayload.provider,'rules');assert.equal(offlinePayload.candidates.length,2);
(globalThis as any).window.__STARSCORE_HTML_PREVIEW__=true;
const accepted=applyResponseCandidate(project,payload.candidates[0]!,'rules',project.seedRevision);
assert.deepEqual(validateProject(accepted),[]);
assert.equal(accepted.tracks.lead.events.length,12);
assert.deepEqual(userNotes(accepted),userNotes(project));
let state=initialStudioState(project);
state=studioReducer(state,{type:'acceptResponse',candidate:payload.candidates[0]!,provider:'rules',seedRevision:project.seedRevision});
assert.equal(state.project.tracks.lead.events.length,12);
state=studioReducer(state,{type:'undo'});
assert.deepEqual(state.project,project);
state=studioReducer(state,{type:'redo'});
assert.equal(state.project.tracks.lead.events.length,12);
state=studioReducer(state,{type:'duration',id:'night-1',durationTick:240});
assert.equal(userNotes(state.project)[1]!.startTick,240);
state=studioReducer(state,{type:'velocity',id:'night-1',velocity:.3});
assert.equal(userNotes(state.project)[0]!.velocity,.3);
assert.deepEqual(validateProject(state.project),[]);
const json=exportProjectJson(accepted), imported=importProjectJson(json);
assert.equal(imported.ok,true);
if(imported.ok){assert.deepEqual(imported.project.tracks,accepted.tracks);assert.deepEqual(imported.project.layout,accepted.layout)}
assert.equal(importProjectJson('{broken').ok,false);
const midi=exportProjectMidi(accepted),parsed=inspectMidi(midi);
assert.ok(Math.abs((parsed.bpm??0)-90)<.001);
assert.deepEqual(parsed.timeSignature,[4,4]);assert.equal(parsed.tracks.length,3);assert.equal(parsed.tracks[0]!.notes.length,24);
assert.ok(parsed.meta.some(event=>event.type==='marker'&&event.text==='StarScore 8-bar loop end'));
const jsonHref=downloadHref(json,'application/json','example.json');
assert.equal(Buffer.from(jsonHref.split(',')[1]!,'base64').toString(),json);
const midiHref=downloadHref(midi,'audio/midi','example.mid');
assert.deepEqual(Buffer.from(midiHref.split(',')[1]!,'base64'),Buffer.from(midi));
const cancelled=new AbortController();cancelled.abort();
await assert.rejects(requestResponses(request,cancelled.signal),{name:'AbortError'});
await assert.rejects(requestResponses({...request,mode:'model'},new AbortController().signal),/真实 AI/);
console.log('PASS: legal rules candidates, acceptance/undo/redo, duration/velocity edits, JSON round-trip, 3-track 8-bar MIDI, download bytes and cancellation.');
