import assert from "node:assert/strict";
import { validateImportedProject } from "@starscore/core";
import { addFriendGalaxy, createGalaxyBundle, emptyGalaxyState, exampleGalaxies, GALAXY_FILE_LIMIT, GALAXY_IMPORT_LIMIT, galaxyResidents, parseGalaxyFile, readGalaxyState, selectGalaxies, serializeGalaxy, validateGalaxyBundle, workKey, writeGalaxyState, type GalaxyProfile } from "../apps/web/src/community/galaxy";

assert.equal(exampleGalaxies.length,7);
for(const galaxy of exampleGalaxies){assert.equal(validateGalaxyBundle(galaxy).ok,true);for(const work of galaxy.works)assert.equal(validateImportedProject(work.project).ok,true)}
const examplesBefore=JSON.stringify(exampleGalaxies);
const profile:GalaxyProfile={id:"galaxy-check",name:"测试旅人",title:"测试星云",bio:"分享两段星谱",color:"#95d8d4",mood:"空灵"};
const originals=exampleGalaxies[0]!.works.map(work=>structuredClone(work.project));
(originals[0] as any).privateToken="must-not-be-shared";
(originals[0]!.tracks.lead as any).privateToken="must-not-be-shared";
(originals[0]!.music as any).privateToken="must-not-be-shared";
const bundle=createGalaxyBundle(profile,originals);
assert.equal(bundle.works.length,2);
assert.equal(serializeGalaxy(bundle).includes("must-not-be-shared"),false);
originals[0]!.title="changed after publishing";originals[0]!.tracks.lead.events[0]!.pitch=72;
assert.notEqual(bundle.works[0]!.project.title,originals[0]!.title);
assert.equal(bundle.works[0]!.project.tracks.lead.events[0]!.pitch,60);
const parsed=parseGalaxyFile(serializeGalaxy(bundle));assert.equal(parsed.ok,true);if(parsed.ok)assert.deepEqual(parsed.bundle,bundle);
assert.equal(parseGalaxyFile("{broken").ok,false);
assert.equal(parseGalaxyFile("x".repeat(GALAXY_FILE_LIMIT+1)).ok,false);
assert.equal(validateGalaxyBundle({...bundle,version:2}).ok,false);
assert.equal(validateGalaxyBundle({...bundle,profile:{...profile,color:"red;url(x)"}}).ok,false);
assert.equal(validateGalaxyBundle({...bundle,works:[]}).ok,false);
assert.equal(validateGalaxyBundle({...bundle,works:Array(9).fill(bundle.works[0])}).ok,false);
assert.equal(validateGalaxyBundle({...bundle,works:[bundle.works[0],bundle.works[0]]}).ok,false);
const bad=structuredClone(bundle);(bad.works[0]!.project.tracks.lead.events as any[])[0]=null;
assert.equal(validateGalaxyBundle(bad).ok,false,"Malformed nested events must fail safely rather than throw");
const storage=new Map<string,string>();let full=false;
(globalThis as any).localStorage={getItem:(key:string)=>storage.get(key)??null,setItem:(key:string,value:string)=>{if(full)throw new Error("quota");storage.set(key,value)}};
const state={...emptyGalaxyState(),own:bundle};
assert.equal(writeGalaxyState(state),true);assert.deepEqual(readGalaxyState(),state);
const friend=createGalaxyBundle({...profile,id:"friend-check",name:"好友"},bundle.works.map(work=>work.project));
const withFriend=addFriendGalaxy(state,friend);
assert.equal(withFriend.friends.length,1);assert.equal(state.friends.length,0);
const updated=createGalaxyBundle({...friend.profile,title:"更新星云"},friend.works.map(work=>work.project));
const replaced=addFriendGalaxy(withFriend,updated);assert.equal(replaced.friends.length,1);assert.equal(replaced.friends[0]!.profile.title,"更新星云");
assert.throws(()=>addFriendGalaxy(withFriend,bundle),/自己的星系/);
const reserved=createGalaxyBundle({...friend.profile,id:exampleGalaxies[0]!.profile.id},friend.works.map(work=>work.project));
const residents=galaxyResidents(addFriendGalaxy(withFriend,reserved));
assert.equal(new Set(residents.map(galaxy=>galaxy.id)).size,residents.length);
assert.equal(residents.find(galaxy=>galaxy.id===exampleGalaxies[0]!.id)?.source,"example");
assert.equal(selectGalaxies(residents,"更新星云","全部","all",[]).length,0);
assert.equal(selectGalaxies(galaxyResidents(replaced),"更新星云","全部","all",[]).length,1);
assert.equal(selectGalaxies(residents,"","全部","mine",[])[0]!.id,"mine");
assert.equal(selectGalaxies(residents,"","全部","following",["example-luna"]).length,1);
assert.notEqual(workKey("a","bc"),workKey("ab","c"));
const many={...state,friends:Array.from({length:GALAXY_IMPORT_LIMIT},(_,i)=>createGalaxyBundle({...friend.profile,id:`friend-${i}`},friend.works.map(work=>work.project)))};
assert.throws(()=>addFriendGalaxy(many,friend),/12/);
full=true;assert.equal(writeGalaxyState(withFriend),false);assert.deepEqual(readGalaxyState(),state);full=false;
assert.equal(JSON.stringify(exampleGalaxies),examplesBefore);
console.log("PASS: seven playable example clouds, selective immutable music snapshots, safe share-file round-trip, malformed/oversize import rejection, profile namespaces, friend updates, limits and storage-failure integrity.");
