import assert from "node:assert/strict";
import { createResponseRequest, exportProjectJson, importProjectJson, userNotes, validateImportedProject, validateProject } from "@starscore/core";
import { catalogItems, createCatalogProject, createMaterialCopy, selectCatalogItems } from "../apps/web/src/catalog/catalog";
import { readFavoriteIds, writeFavoriteIds } from "../apps/web/src/catalog/favorites";
import { initialStudioState, studioReducer } from "../apps/web/src/studio/studioReducer";
import { exportProjectMidi, inspectMidi } from "../apps/web/src/files/midi";
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";

assert.equal(catalogItems.filter(item=>item.kind==="zodiac").length,12);
assert.equal(catalogItems.filter(item=>item.kind==="materials").length,6);
assert.equal(new Set(catalogItems.map(item=>item.id)).size,18);
assert.equal(new Set(catalogItems.map(item=>JSON.stringify([item.pitches,item.beats]))).size,18);
const before=JSON.stringify(catalogItems);
for(const item of catalogItems){
  const project=createCatalogProject(item,true);
  assert.deepEqual(validateProject(project),[],item.id);
  const checked=validateImportedProject(project);assert.equal(checked.ok,true,checked.ok?item.id:checked.message);
  const originals=userNotes(project),reply=project.tracks.lead.events.filter(note=>note.origin!=="user");
  assert.equal(originals.at(-1)!.startTick+originals.at(-1)!.durationTick,3840,item.id);
  assert.equal(reply.at(-1)!.startTick+reply.at(-1)!.durationTick,7680,item.id);
  const imported=importProjectJson(exportProjectJson(project));assert.equal(imported.ok,true);
  if(imported.ok){assert.deepEqual(imported.project.tracks,project.tracks);assert.deepEqual(imported.project.mixer,project.mixer)}
  const parsed=inspectMidi(exportProjectMidi(project));
  assert.ok(Math.abs((parsed.bpm??0)-90)<.001);assert.deepEqual(parsed.timeSignature,[4,4]);
  assert.equal(parsed.tracks.length,3);assert.equal(parsed.tracks[0]!.notes.length,project.tracks.lead.events.length*2);
  assert.equal(parsed.tracks[1]!.notes.length,project.tracks.bass.events.length*2);
  assert.equal(parsed.tracks[2]!.notes.length,project.tracks.drums.events.length*2);
  assert.equal(createResponseRequest(project,"catalog-check","rules").notes.length,originals.length);
  const copy=createMaterialCopy(item);assert.notEqual(copy.id,project.id);assert.ok(copy.title.endsWith("我的版本"));
  assert.deepEqual(copy.tracks,project.tracks);
  let state=initialStudioState(copy);
  state=studioReducer(state,{type:"dragStart"});
  state=studioReducer(state,{type:"move",id:originals[0]!.id,pitch:72,xNorm:.21});
  state=studioReducer(state,{type:"dragCommit"});
  assert.deepEqual(state.project.tracks.lead.events.filter(note=>note.origin!=="user"),reply,"moving a seed must preserve the preset response");
  assert.equal(validateImportedProject(state.project).ok,true,"edited material must remain importable");
  state=studioReducer(state,{type:"undo"});assert.deepEqual(state.project,copy);
}
assert.equal(JSON.stringify(catalogItems),before,"using a preset must never mutate the catalog");
const taurus=catalogItems.find(item=>item.id==="taurus")!;
let state=initialStudioState(createMaterialCopy(taurus));
const response=state.project.tracks.lead.events.filter(note=>note.origin!=="user");
state=studioReducer(state,{type:"duration",id:"taurus-seed-5",durationTick:480});
state=studioReducer(state,{type:"add",pitch:64,xNorm:.4});
assert.equal(userNotes(state.project).length,7);
assert.deepEqual(state.project.tracks.lead.events.filter(note=>note.origin!=="user"),response);
assert.equal(validateImportedProject(state.project).ok,true);
assert.equal(selectCatalogItems("zodiac","","火象").length,3);
assert.equal(selectCatalogItems("zodiac","pisces")[0]!.label,"双鱼座");
assert.equal(selectCatalogItems("materials","晚安")[0]!.id,"goodnight-asteroid");
assert.equal(selectCatalogItems("materials","","抒情").length,2);
assert.deepEqual(selectCatalogItems("zodiac","","全部",["pisces"]).map(item=>item.id),["pisces"]);
assert.deepEqual(selectCatalogItems("zodiac","不存在的素材"),[]);
const storage=new Map<string,string>();
(globalThis as any).localStorage={getItem:(key:string)=>storage.get(key)??null,setItem:(key:string,value:string)=>storage.set(key,value)};
assert.equal(writeFavoriteIds(["pisces","rain-cafe"]),true);
assert.deepEqual(readFavoriteIds(),["pisces","rain-cafe"]);
storage.set("starscore-catalog-favorites-v1",'["pisces","unknown","pisces",44]');
assert.deepEqual(readFavoriteIds(),["pisces"]);
storage.set("starscore-catalog-favorites-v1","{broken");assert.deepEqual(readFavoriteIds(),[]);
(globalThis as any).window={__STARSCORE_HTML_PREVIEW__:true};
(globalThis as any).matchMedia=()=>({matches:false});
(globalThis as any).location={hash:"#/discover/zodiac"};
const {App}=await import("../apps/web/src/App");
const zodiacHtml=renderToStaticMarkup(createElement(App));
assert.equal((zodiacHtml.match(/class="collection-card /g)??[]).length,12);
assert.ok(zodiacHtml.includes("十二星座主题曲"));assert.ok(zodiacHtml.includes("星谱功能导航"));
assert.ok(zodiacHtml.includes("用 白羊座 创作"));
(globalThis as any).location.hash="#/discover/materials";
const materialsHtml=renderToStaticMarkup(createElement(App));
assert.equal((materialsHtml.match(/class="collection-card /g)??[]).length,6);
assert.ok(materialsHtml.includes("雨夜咖啡"));assert.ok(materialsHtml.includes("搜索星谱"));
console.log("PASS: 12 zodiac themes + 6 original materials; unique motifs, complete 4-bar scores, compatible JSON/MIDI, independent copies, editable seeds with replies retained, favorites/search/filter and routed page rendering.");
